apiVersion: v1 # Where in the API it resides
kind: Service # The kind of workload we're creating
metadata:
  name: dnmonster # This will be the name of the deployment
spec:
  type: ClusterIP
  selector: # Define the wrapping srategy
    app: dnmonster-pod # Labels follow the `name: value` template
  ports:
    - port: 8080 # SERVICE exposed port
      protocol: TCP # The protocol the SERVICE will listen to
      targetPort: 8080 # Port to forward to in the POD

